import { formatCents, parseEuroToCents } from '../../js/utils.js';
import { loadCapyConfig } from './config.js';
import { addJournal, applyRemoteCapy, availableCoins, loadCapyState, queueCoinOp, saveCapyState, setCapyEnabled, touchCare } from './shared-state.js';
import { applyElapsedDecay, applyItem, applyPet, applyPlay, canPlay, chooseVisual, currentPhase, genderCopy } from './engine.js';
import { createStashDeposit, loadFinanceContext, stashBalanceCents } from './finance-adapter.js';
import { createPetSession, itemEffectLabel, movePetSession, petRewardForSession, pointInRect } from './interactions.js';

const $=id=>document.getElementById(id);
const els={
  inactiveState:$('inactiveState'),inactiveTitle:$('inactiveTitle'),inactiveCopy:$('inactiveCopy'),enabledState:$('enabledState'),capyName:$('capyName'),capyMeta:$('capyMeta'),coinIconTop:$('coinIconTop'),coinCountTop:$('coinCountTop'),coinCountShop:$('coinCountShop'),
  hungerValue:$('hungerValue'),happinessValue:$('happinessValue'),energyValue:$('energyValue'),bondValue:$('bondValue'),hungerBar:$('hungerBar'),happinessBar:$('happinessBar'),energyBar:$('energyBar'),bondBar:$('bondBar'),phasePill:$('phasePill'),moodValue:$('moodValue'),statusHint:$('statusHint'),
  scene:$('scene'),capyImage:$('capyImage'),effectsLayer:$('effectsLayer'),floatingLayer:$('floatingLayer'),dropHint:$('dropHint'),playButton:$('playButton'),inventoryBadge:$('inventoryBadge'),shopList:$('shopList'),inventoryList:$('inventoryList'),journalList:$('journalList'),
  vorratName:$('vorratName'),stashValue:$('stashValue'),stashLocked:$('stashLocked'),stashWithdrawable:$('stashWithdrawable'),stashUnlockHint:$('stashUnlockHint'),topUpAmount:$('topUpAmount'),coinRewardHint:$('coinRewardHint'),topUpButton:$('topUpButton'),capyTransactions:$('capyTransactions'),pauseCapyButton:$('pauseCapyButton'),
  setupModal:$('setupModal'),nameInput:$('nameInput'),genderInfo:$('genderInfo'),finishSetupButton:$('finishSetupButton'),creatorPreview:$('creatorPreview'),genderButtons:[...document.querySelectorAll('[data-gender]')],
  sheets:[...document.querySelectorAll('[data-sheet]')],dragGhost:$('dragGhost'),toast:$('toast')
};

let config,capy,plan=null,transactions=[];let runtimeVisual='',runtimeTimer=0,toastTimer=0,setupGender='männlich';let petSession=null,lastPetRewardAt=0;let drag=null;

boot().catch(error=>{console.error(error);document.body.insertAdjacentHTML('afterbegin',`<div style="padding:1rem;background:#8b1e35;color:white">Capy konnte nicht gestartet werden: ${escapeHtml(error.message)}</div>`);});

async function boot(){
  config=await loadCapyConfig();capy=await loadCapyState(config.behavior.initialNeeds);await refreshFinance(true);configureVisualAssets();bindEvents();
  if(capy.enabled&&capy.care.initialized){applyElapsedDecay(capy.care,config.behavior);touchCare(capy);capy=await saveCapyState(capy);}
  renderAll();if(capy.enabled&&!capy.care.initialized)openCreator();
  setInterval(async()=>{if(!capy.enabled||!capy.care.initialized)return;applyElapsedDecay(capy.care,config.behavior);touchCare(capy);capy=await saveCapyState(capy);renderAll();},Math.max(15000,Number(config.behavior.decayTickMs)||60000));
  document.addEventListener('visibilitychange',async()=>{if(document.visibilityState!=='visible')return;await refreshFinance(true);if(capy.enabled&&capy.care.initialized){applyElapsedDecay(capy.care,config.behavior);touchCare(capy);capy=await saveCapyState(capy);}renderAll();});
}

async function refreshFinance(applyRemote=false){
  const finance=await loadFinanceContext();plan=finance.plan;transactions=finance.transactions;
  if(applyRemote){capy=applyRemoteCapy(capy,plan?.capy||{enabled:false},plan?.acknowledgedExportIds||[],plan?.transactionResults||[]);capy=await saveCapyState(capy);}
}

function configureVisualAssets(){
  const iconPath=String(config.economy.coinImage||'');if(iconPath){els.coinIconTop.src=iconPath;els.coinIconTop.addEventListener('error',()=>{els.coinIconTop.hidden=true;},{once:true});}else els.coinIconTop.hidden=true;
  const room=config.behavior.room||{};if(room.backgroundImage){els.scene.style.backgroundImage=`url("${String(room.backgroundImage).replaceAll('"','\\"')}")`;els.scene.style.backgroundPosition=room.backgroundPosition||'center';els.scene.style.backgroundSize=room.backgroundSize||'cover';}
  const rate=Number(config.economy.coinsPerEuro)||1;els.coinRewardHint.textContent=`1,00 € = ${formatCoin(rate)} Coin${rate===1?'':'s'} · Coins sind vom Echtgeld-Vorrat getrennt.`;
  document.documentElement.style.setProperty('--drag-return-ms',`${Math.max(0,Number(config.behavior.inventoryDrag?.returnAnimationMs)||180)}ms`);
}

function bindEvents(){
  document.querySelectorAll('[data-open-sheet]').forEach(button=>button.addEventListener('click',()=>openSheet(button.dataset.openSheet)));
  document.querySelectorAll('[data-close-sheet]').forEach(button=>button.addEventListener('click',()=>button.closest('dialog')?.close()));
  els.sheets.forEach(sheet=>sheet.addEventListener('pointerdown',event=>{if(event.target===sheet)sheet.close();}));
  document.querySelector('[data-open-main="settings"]')?.addEventListener('click',()=>{location.href='../#/settings';});
  els.playButton.addEventListener('click',()=>void playCapy());els.topUpButton.addEventListener('click',()=>void topUpVorrat());els.pauseCapyButton.addEventListener('click',()=>void pauseCapy());
  els.genderButtons.forEach(button=>button.addEventListener('click',()=>selectSetupGender(button.dataset.gender)));els.finishSetupButton.addEventListener('click',()=>void finishSetup());els.nameInput.addEventListener('keydown',event=>{if(event.key==='Enter'){event.preventDefault();void finishSetup();}});els.setupModal.addEventListener('cancel',event=>event.preventDefault());
  els.capyImage.addEventListener('pointerdown',onPetDown);els.capyImage.addEventListener('pointermove',onPetMove);els.capyImage.addEventListener('pointerup',onPetEnd);els.capyImage.addEventListener('pointercancel',onPetCancel);els.capyImage.addEventListener('dragstart',event=>event.preventDefault());
}

function openCreator(){setupGender=(config.behavior.genders||[]).includes('männlich')?'männlich':'weiblich';selectSetupGender(setupGender);els.nameInput.value=capy.care.name||'';if(!els.setupModal.open)els.setupModal.showModal();setTimeout(()=>els.nameInput.focus(),100);}
function selectSetupGender(gender){if(!['männlich','weiblich'].includes(gender))return;setupGender=gender;els.genderButtons.forEach(button=>button.classList.toggle('is-active',button.dataset.gender===gender));const info=genderCopy(gender);els.genderInfo.textContent=`${info.mark} ${info.label} ausgewählt · gespeichert wird erst mit „Capy erstellen“.`;}
async function finishSetup(){const name=els.nameInput.value.trim();if(!name){showToast('Bitte gib deinem Capy einen Namen.');els.nameInput.focus();return;}if(!['männlich','weiblich'].includes(setupGender)){showToast('Bitte wähle männlich oder weiblich.');return;}capy.care.initialized=true;capy.care.name=name.slice(0,20);capy.care.gender=setupGender;capy.care.lastUpdate=Date.now();addJournal(capy,'home',`${capy.care.name} ist eingezogen.`,config.behavior.maxJournalEntries);touchCare(capy);capy=await saveCapyState(capy);els.setupModal.close();setRuntimeVisual('celebrate',animationMs('celebrate',1300),'capy--celebrate');spawnEffect('confetti',36,28,true);spawnEffect('sparkle',66,24,true);showFloating(`${capy.care.name} ist da!`,50,42);renderAll();}

function openSheet(id){if(!capy.enabled||!capy.care.initialized)return;const target=$(id);if(!target)return;els.sheets.forEach(sheet=>{if(sheet!==target&&sheet.open)sheet.close();});if(!target.open)target.showModal();if(id==='inventorySheet')renderInventory();if(id==='shopSheet')renderShop();if(id==='stashSheet')renderWallet();if(id==='moreSheet')renderJournal();}

function petBlocked(){const phase=currentPhase(config.behavior);return phase.key==='night'&&config.behavior.sleep?.blocksPet!==false;}
function onPetDown(event){if(!capy.enabled||!capy.care.initialized||config.behavior.petting?.enabled===false)return;if(petBlocked()){spawnEffect('zzz',68,24,false);showToast(`${capy.care.name||'Capy'} schläft.`);return;}petSession=createPetSession(event.pointerId,event.clientX,event.clientY);els.capyImage.classList.add('is-petting');els.capyImage.setPointerCapture?.(event.pointerId);event.preventDefault();}
function onPetMove(event){if(!petSession||event.pointerId!==petSession.pointerId)return;movePetSession(petSession,event.clientX,event.clientY);const reward=petRewardForSession(petSession,config.behavior.petting,capy.care.happiness,lastPetRewardAt,Date.now());if(reward>0){petSession.awarded+=reward;petSession.distance=0;lastPetRewardAt=Date.now();void awardPet(reward);}event.preventDefault();}
async function awardPet(reward){applyPet(capy.care,config.behavior,reward);addJournal(capy,'heart',`${capy.care.name||'Capy'} wurde gestreichelt.`,config.behavior.maxJournalEntries);touchCare(capy);capy=await saveCapyState(capy);animateCapy('capy--pet',animationMs('pet',520));spawnEffect('heart',61,30,true);showFloating(`+${reward} ❤️`,58,34);renderAll();}
function onPetEnd(event){if(!petSession||event.pointerId!==petSession.pointerId)return;petSession.active=false;petSession=null;els.capyImage.classList.remove('is-petting');try{els.capyImage.releasePointerCapture?.(event.pointerId);}catch{}event.preventDefault();}
function onPetCancel(event){if(!petSession||event.pointerId!==petSession.pointerId)return;petSession.active=false;petSession=null;els.capyImage.classList.remove('is-petting');}

async function playCapy(){if(currentPhase(config.behavior).key==='night'&&config.behavior.sleep?.blocksPlay!==false){showToast(`${capy.care.name||'Capy'} schläft.`);return;}if(!canPlay(capy.care,config.behavior)){showToast(`${capy.care.name||'Capy'} ist zu müde zum Spielen.`);return;}const before={happiness:capy.care.happiness,energy:capy.care.energy};applyPlay(capy.care,config.behavior);addJournal(capy,'play',`${capy.care.name||'Capy'} hat mit dir gespielt.`,config.behavior.maxJournalEntries);touchCare(capy);capy=await saveCapyState(capy);animateCapy('capy--play',animationMs('play',760));spawnEffect('sparkle',38,29,true);showFloating(`${signed(capy.care.happiness-before.happiness)} ❤️  ${signed(capy.care.energy-before.energy)} ⚡`,47,31);renderAll();}

async function buyItem(item){if(!item)return;const price=Math.max(0,Math.floor(Number(item.priceCoins)||0)),count=Math.max(0,Math.floor(Number(capy.care.inventory[item.id])||0));if(availableCoins(capy)<price){showToast('Nicht genug Coins.');return;}if(item.stackable!==false&&count>=item.maxStack){showToast(`${item.name} hat bereits den maximalen Stack.`);return;}queueCoinOp(capy,-price,`${item.name} gekauft`);capy.care.inventory[item.id]=count+1;addJournal(capy,'shop',`${item.name} für ${price} Coins gekauft.`,config.behavior.maxJournalEntries);touchCare(capy);capy=await saveCapyState(capy);showFloating(`-${price} 🪙   +1`,50,48);renderAll();showToast(`${item.name} liegt jetzt im Inventar.`);}

function bindInventoryDrag(){els.inventoryList.querySelectorAll('[data-drag-item]').forEach(node=>node.addEventListener('pointerdown',event=>startItemPointer(event,node.dataset.dragItem)));}
function startItemPointer(event,itemId){const item=config.items.find(x=>x.id===itemId),count=Math.max(0,Math.floor(Number(capy.care.inventory[itemId])||0));if(!item||count<1)return;const source=event.currentTarget.getBoundingClientRect(),holdDelay=Math.max(0,Number(config.behavior.inventoryDrag?.holdDelayMs)||120);drag={pointerId:event.pointerId,item,startX:event.clientX,startY:event.clientY,x:event.clientX,y:event.clientY,source,startedAt:Date.now(),active:false,used:false,timer:0,node:event.currentTarget};event.currentTarget.setPointerCapture?.(event.pointerId);drag.timer=setTimeout(()=>activateDrag(event.clientX,event.clientY),holdDelay);event.currentTarget.addEventListener('pointermove',moveItemPointer);event.currentTarget.addEventListener('pointerup',endItemPointer,{once:true});event.currentTarget.addEventListener('pointercancel',cancelItemPointer,{once:true});event.preventDefault();}
function activateDrag(x,y){if(!drag||drag.active)return;drag.active=true;const count=Math.max(0,Math.floor(Number(capy.care.inventory[drag.item.id])||0));els.dragGhost.querySelector('img').src=drag.item.asset;els.dragGhost.querySelector('span').textContent=`x${count}`;els.dragGhost.classList.remove('hidden','is-returning');positionGhost(x,y);updateDropTarget(x,y);}
function moveItemPointer(event){if(!drag||event.pointerId!==drag.pointerId)return;drag.x=event.clientX;drag.y=event.clientY;const threshold=Math.max(0,Number(config.behavior.inventoryDrag?.movementThreshold)||6),moved=Math.hypot(drag.x-drag.startX,drag.y-drag.startY);if(!drag.active&&moved>=threshold&&Date.now()-drag.startedAt>=Math.max(0,Number(config.behavior.inventoryDrag?.holdDelayMs)||120))activateDrag(drag.x,drag.y);if(drag.active){positionGhost(drag.x,drag.y);updateDropTarget(drag.x,drag.y);}event.preventDefault();}
function positionGhost(x,y){els.dragGhost.style.left=`${x}px`;els.dragGhost.style.top=`${y}px`;}
function updateDropTarget(x,y){const over=pointInRect(x,y,els.capyImage.getBoundingClientRect());els.scene.classList.toggle('is-drop-active',over);els.capyImage.classList.toggle('is-drop-target',over);return over;}
async function endItemPointer(event){if(!drag||event.pointerId!==drag.pointerId)return;clearTimeout(drag.timer);const current=drag,node=drag.node;cleanupPointerListeners(node);if(current.active&&updateDropTarget(event.clientX,event.clientY)&&!current.used){current.used=true;cleanupDragVisual();drag=null;await useItem(current.item);}else{if(current.active)returnGhost(current);else cleanupDragVisual();drag=null;}try{node.releasePointerCapture?.(event.pointerId);}catch{}event.preventDefault();}
function cancelItemPointer(event){if(!drag||event.pointerId!==drag.pointerId)return;clearTimeout(drag.timer);const current=drag,node=drag.node;cleanupPointerListeners(node);if(current.active)returnGhost(current);else cleanupDragVisual();drag=null;try{node.releasePointerCapture?.(event.pointerId);}catch{}}
function cleanupPointerListeners(node){node?.removeEventListener('pointermove',moveItemPointer);}
function returnGhost(current){const x=current.source.left+current.source.width/2,y=current.source.top+current.source.height/2;els.dragGhost.classList.add('is-returning');positionGhost(x,y);setTimeout(()=>{cleanupDragVisual();if(drag===current)drag=null;},Math.max(0,Number(config.behavior.inventoryDrag?.returnAnimationMs)||180));}
function cleanupDragVisual(){els.scene.classList.remove('is-drop-active');els.capyImage.classList.remove('is-drop-target');els.dragGhost.classList.add('hidden');els.dragGhost.classList.remove('is-returning');}

async function useItem(item){const count=Math.max(0,Math.floor(Number(capy.care.inventory[item.id])||0));if(count<1){showToast(`${item.name} ist nicht mehr im Inventar.`);return;}const phase=currentPhase(config.behavior);if(item.type==='food'&&phase.key==='night'&&config.behavior.sleep?.blocksFood!==false){showToast(`${capy.care.name||'Capy'} schläft gerade.`);return;}if(item.type==='toy'&&phase.key==='night'&&config.behavior.sleep?.blocksPlay!==false){showToast(`${capy.care.name||'Capy'} schläft gerade.`);return;}
  capy.care.inventory[item.id]=count-1;const delta=applyItem(capy.care,item);addJournal(capy,item.type,`${capy.care.name||'Capy'} hat ${item.name} benutzt.`,config.behavior.maxJournalEntries);touchCare(capy);capy=await saveCapyState(capy);
  const animation=item.interaction?.animation||'eat';if(animation==='eat'){setRuntimeVisual('eating',animationMs('feed',900),'capy--feed');spawnEffect('heart',63,31,false);}else if(animation==='play'){animateCapy('capy--play',animationMs('play',760));spawnEffect('sparkle',40,30,true);}else{animateCapy('capy--care',animationMs('pet',520));spawnEffect('heart',60,30,false);}
  showFloating(effectFeedback(delta),54,33);renderAll();showToast(`${item.name} erfolgreich benutzt.`);
}

async function topUpVorrat(){const cents=parseEuroToCents(els.topUpAmount.value),minimum=Math.max(1,Number(config.economy.minimumTopUpCents)||100);if(!Number.isSafeInteger(cents)||cents<minimum){showToast(`Mindestens ${formatCents(minimum)} aufladen.`);return;}if(!plan?.capy?.budgetId){showToast('Bitte zuerst einen aktuellen Capy-Plan synchronisieren.');return;}const coins=Math.max(1,Math.floor((cents/100)*(Number(config.economy.coinsPerEuro)||1)));try{const tx=await createStashDeposit({plan,amountCents:cents,name:capy.care.name||'Capy',coinReward:coins});queueCoinOp(capy,coins,`Vorrat +${formatCents(cents)}`,tx.id);addJournal(capy,'coin',`${formatCents(cents)} in ${vorratName()} gelegt · ${coins} Coins warten auf PC-Bestätigung.`,config.behavior.maxJournalEntries);touchCare(capy);capy=await saveCapyState(capy);els.topUpAmount.value='';await refreshFinance(false);renderAll();spawnEffect('coin',50,34,true);showFloating(`+${coins} 🪙`,50,35);showToast('Buchung ist sofort unter Buchungen sichtbar und wartet auf den PC.');}catch(error){showToast(error.message);}}

async function pauseCapy(){const name=capy.care.name||'Capy';if(!confirm(`Capy-Begleiter pausieren?\n\n${name} und dein Fortschritt bleiben gespeichert. Während der Pause verändern sich seine Bedürfnisse nicht.`))return;setCapyEnabled(capy,false);capy=await saveCapyState(capy);els.sheets.forEach(sheet=>sheet.open&&sheet.close());renderAll();showToast(`${name} pausiert. Der Zustand wird beim nächsten FP1-Sync übertragen.`);}

function renderAll(){const active=Boolean(capy.enabled);els.inactiveState.classList.toggle('hidden',active);els.enabledState.classList.toggle('hidden',!active);if(!active){const initialized=Boolean(capy.care.initialized);els.inactiveTitle.textContent=initialized?`${capy.care.name||'Capy'} · pausiert`:'Capy · Alpha';els.inactiveCopy.textContent=initialized?'Dein Capy und sein Fortschritt bleiben gespeichert. Vorrat, Sperren und ausstehende Finanztransaktionen bleiben erhalten.':'Aktiviere Capy am PC unter Grundlagen und synchronisiere den Plan mit diesem Gerät.';return;}renderProfile();renderNeeds();renderWallet();renderShop();renderInventory();renderJournal();renderCapy();}
function renderProfile(){const phase=currentPhase(config.behavior),gender=genderCopy(capy.care.gender),name=capy.care.initialized?capy.care.name:'Capy';els.capyName.textContent=name;els.capyMeta.textContent=capy.care.initialized?`${gender.mark} ${gender.label} · Capy · Alpha`:'Capy · Alpha';els.phasePill.textContent=phase.label;}
function renderNeeds(){setNeed(els.hungerValue,els.hungerBar,capy.care.hunger);setNeed(els.happinessValue,els.happinessBar,capy.care.happiness);setNeed(els.energyValue,els.energyBar,capy.care.energy);setNeed(els.bondValue,els.bondBar,capy.care.bond);}
function renderWallet(){const coins=availableCoins(capy),stash=stashBalanceCents(plan,transactions),name=vorratName();const pendingLocked=(transactions||[]).filter(t=>!t.deleted&&t.status!=='confirmed'&&t.status!=='rejected'&&t.kind==='capy_stash_deposit').reduce((sum,t)=>sum+(Number(t.amountCents)||0),0),locked=Math.max(0,Number(plan?.capy?.lockedStashCents)||0)+pendingLocked,withdrawable=Math.max(0,Number(plan?.capy?.withdrawableStashCents)||0);els.coinCountTop.textContent=formatCoin(coins);els.coinCountShop.textContent=formatCoin(coins);els.vorratName.textContent=name;els.stashValue.textContent=formatCents(stash);els.stashLocked.textContent=formatCents(Math.min(stash,locked));els.stashWithdrawable.textContent=formatCents(Math.min(stash,withdrawable));els.stashUnlockHint.textContent=plan?.capy?.nextUnlockDate?`Nächste Freigabe: ${formatDate(plan.capy.nextUnlockDate)}`:`Einzahlungen bleiben ${Math.max(0,Number(plan?.capy?.stashLockMonths??config.economy.stashLockMonths)||0)} Monat${Number(plan?.capy?.stashLockMonths??config.economy.stashLockMonths)===1?'':'e'} gesperrt.`;renderCapyTransactions();}
function renderShop(){const coins=availableCoins(capy);els.shopList.innerHTML=config.items.length?config.items.map(item=>{const price=Math.max(0,Math.floor(Number(item.priceCoins)||0)),count=Math.max(0,Math.floor(Number(capy.care.inventory[item.id])||0));return `<article class="shop-item"><img src="${escapeHtml(item.asset)}" alt=""><div class="shop-item-copy"><strong>${escapeHtml(item.name)}</strong><span class="item-type">${escapeHtml(typeLabel(item.type))}</span><small>${escapeHtml(itemEffectLabel(item))}</small></div><button type="button" data-buy="${escapeHtml(item.id)}" ${coins<price||count>=item.maxStack?'disabled':''}>${price} 🪙 · Kaufen</button></article>`;}).join(''):'<div class="empty">Keine Items aktiviert.</div>';els.shopList.querySelectorAll('[data-buy]').forEach(button=>button.addEventListener('click',()=>void buyItem(config.items.find(item=>item.id===button.dataset.buy))));}
function renderInventory(){const rows=config.items.map(item=>({item,count:Math.max(0,Math.floor(Number(capy.care.inventory[item.id])||0))})).filter(row=>row.count>0),total=rows.reduce((sum,row)=>sum+row.count,0);els.inventoryBadge.textContent=String(total);els.inventoryBadge.classList.toggle('hidden',total<1);els.inventoryList.innerHTML=rows.length?rows.map(({item,count})=>`<div class="inventory-item" data-drag-item="${escapeHtml(item.id)}"><img src="${escapeHtml(item.asset)}" alt=""><div><strong>${escapeHtml(item.name)}</strong><small>${escapeHtml(itemEffectLabel(item))}</small><em>x${count}</em></div></div>`).join(''):'<div class="empty">Noch keine Items. Kaufe etwas im Shop.</div>';bindInventoryDrag();}
function renderJournal(){const rows=capy.care.journal||[];els.journalList.innerHTML=rows.length?rows.slice(0,24).map(entry=>`<div class="journal-entry"><span>${journalIcon(entry.type)}</span><div><small>${escapeHtml(entry.time||'')}</small><p>${escapeHtml(entry.text||'')}</p></div></div>`).join(''):'<div class="empty">Noch keine Ereignisse.</div>';}
function renderCapyTransactions(){const rows=(transactions||[]).filter(t=>!t.deleted&&t.kind==='capy_stash_deposit').slice(0,20);els.capyTransactions.innerHTML=rows.length?rows.map(t=>{const status=t.status==='confirmed'?'✓ Gebucht':t.status==='rejected'?`⚠ Nicht übernommen${t.rejectionReason?` · ${escapeHtml(t.rejectionReason)}`:''}`:'🔒 Wartet auf PC';const reward=Math.max(0,Math.floor(Number(t.capyCoinReward)||0));return `<div class="capy-tx ${t.status==='rejected'?'rejected':''}"><strong>${escapeHtml(vorratName())}</strong><b>${formatCents(t.amountCents)}</b><small>${status}${reward?` · +${reward} 🪙`:''}</small></div>`;}).join(''):'<div class="empty">Noch keine mobilen Capy-Buchungen.</div>';}
function renderCapy(){const phase=currentPhase(config.behavior),visual=runtimeVisual||chooseVisual(capy.care,phase,config.behavior);els.capyImage.src=`./assets/capy/capy-${visual}.png`;const mood=moodCopy(visual);els.capyImage.alt=`${capy.care.name||'Capy'} – ${mood.label}`;els.moodValue.textContent=mood.label;els.statusHint.textContent=mood.hint;const transient=[...els.capyImage.classList].find(x=>x.startsWith('capy--')&&!['capy--idle','capy--sleeping'].includes(x));els.capyImage.className=`capy ${runtimeVisual?(transient||'capy--idle'):visual==='sleeping'?'capy--sleeping':'capy--idle'}`;if(phase.key==='night'&&!els.effectsLayer.querySelector('.effect--zzz'))spawnEffect('zzz',68,24,false);}

function animationMs(key,fallback){return Math.max(1,Number(config?.behavior?.animationMs?.[key])||fallback);}function setNeed(valueEl,barEl,value){const safe=Math.max(0,Math.min(100,Number(value)||0));valueEl.textContent=`${Math.round(safe)}%`;barEl.style.width=`${safe}%`;}
function vorratName(){return String(plan?.capy?.budgetName||globalThis.CapytCapyNaming?.budgetName(capy.care.name||'Capy')||'Capy-Vorrat');}function formatCoin(value){return new Intl.NumberFormat('de-AT',{maximumFractionDigits:0}).format(Math.max(0,Math.floor(Number(value)||0)));}function formatDate(value){if(!/^\d{4}-\d{2}-\d{2}$/.test(String(value||'')))return '–';const [y,m,d]=String(value).split('-').map(Number);return new Intl.DateTimeFormat('de-AT',{day:'2-digit',month:'long'}).format(new Date(y,m-1,d));}
function moodCopy(visual){const name=capy.care.name||'Capy';return {neutral:{label:'Entspannt',hint:`Streichle ${name} direkt.`},happy:{label:'Glücklich',hint:`${name} fühlt sich richtig wohl.`},hungry:{label:'Hungrig',hint:`Zieh Food aus dem Inventar auf ${name}.`},sleepy:{label:'Müde',hint:`${name} wird langsam schläfrig.`},sleeping:{label:'Schläft',hint:`${name} ruht bis zum Morgen.`},eating:{label:'Mampft',hint:`${name} genießt das Item.`},celebrate:{label:'Feiert',hint:`${name} freut sich.`}}[visual]||{label:'Entspannt',hint:`${name} ist da.`};}
function animateCapy(className,duration){clearTimeout(runtimeTimer);els.capyImage.className=`capy ${className}`;runtimeTimer=setTimeout(()=>{els.capyImage.className='capy capy--idle';renderCapy();},duration);}function setRuntimeVisual(visual,duration,className){runtimeVisual=visual;clearTimeout(runtimeTimer);els.capyImage.className=`capy ${className}`;runtimeTimer=setTimeout(()=>{runtimeVisual='';renderCapy();},duration);}
function spawnEffect(kind,left,top,large){const img=document.createElement('img');img.src=`./assets/effects/${kind}.png`;img.alt='';img.className=`effect effect--${kind}${large?' effect--large':''}`;img.style.left=`${left}%`;img.style.top=`${top}%`;els.effectsLayer.appendChild(img);setTimeout(()=>img.remove(),kind==='zzz'?animationMs('zzz',3300):animationMs('effect',1800));}
function showFloating(text,left=50,top=50){const el=document.createElement('div');el.className='floating-feedback';el.textContent=text;el.style.left=`${left}%`;el.style.top=`${top}%`;els.floatingLayer.appendChild(el);setTimeout(()=>el.remove(),1400);}function showToast(text){clearTimeout(toastTimer);els.toast.textContent=text;els.toast.classList.add('is-visible');toastTimer=setTimeout(()=>els.toast.classList.remove('is-visible'),2800);}
function effectFeedback(delta){const parts=[];if(delta.hunger)parts.push(`${signed(delta.hunger)} 🍎`);if(delta.happiness)parts.push(`${signed(delta.happiness)} ❤️`);if(delta.energy)parts.push(`${signed(delta.energy)} ⚡`);if(delta.bond)parts.push(`${signed(delta.bond)} ✦`);return parts.join('  ')||'✓';}function signed(value){const n=Math.round(Number(value)||0);return `${n>0?'+':''}${n}`;}function typeLabel(type){return {food:'Food',toy:'Spielzeug',care:'Pflege'}[type]||'Item';}function journalIcon(type){return {home:'⌂',heart:'♥',play:'✦',food:'🥕',toy:'🎮',care:'✨',shop:'🛒',coin:'🪙'}[type]||'•';}function escapeHtml(value){return String(value??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[c]));}
