import { escapeHtml, formatCents, formatDateTime, formatMonth, setHidden } from '../utils.js';
import { pendingSummary } from '../services/finance.js';

export function renderSync({plan,transactions,pendingPlan,onAcceptPlan}){
  const s=pendingSummary(transactions,plan); document.getElementById('pendingSyncSummary').innerHTML=`<div class="sync-stat"><span>Nicht bestätigt</span><strong>${s.count}</strong></div><div class="sync-stat"><span>Ausgaben</span><strong>${formatCents(s.expensesCents)}</strong></div>`;
  const button=document.getElementById('generateTransactionCode'); button.disabled=!plan||!s.count;
  const meta=document.getElementById('syncPlanMeta'); meta.innerHTML=plan?`<div><span>Plan</span><strong>${escapeHtml(plan.planName||'Capyt · Finanzplanung')}</strong></div><div><span>Monat</span><strong>${formatMonth(plan.month)}</strong></div><div><span>Revision</span><strong>${plan.revision}</strong></div><div><span>Erstellt</span><strong>${formatDateTime(plan.createdAt)}</strong></div>`:'<div><span>Status</span><strong>Noch kein Plan</strong></div>';
  const preview=document.getElementById('planImportPreview'); if(!pendingPlan){preview.innerHTML='';setHidden(preview,true);} else {preview.innerHTML=`<div class="key-values"><div><span>Plan</span><strong>${escapeHtml(pendingPlan.planName||'Capyt · Finanzplanung')}</strong></div><div><span>Monat</span><strong>${formatMonth(pendingPlan.month)}</strong></div><div><span>Budgets</span><strong>${pendingPlan.budgets.length}</strong></div><div><span>Revision</span><strong>${pendingPlan.revision}</strong></div><div><span>Aktualisiert</span><strong>${formatDateTime(pendingPlan.createdAt)}</strong></div></div>${plan&&pendingPlan.planId===plan.planId&&pendingPlan.revision<plan.revision?'<div class="notice warn">Dieser Planstand ist älter als der aktuell gespeicherte Plan.</div>':''}<button id="acceptPlanButton" class="primary full" type="button">Plan übernehmen</button>`;setHidden(preview,false);preview.querySelector('#acceptPlanButton')?.addEventListener('click',onAcceptPlan);}
}
